### ISSUE TITLE
Outputs Screen Enhancement

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#1385]
This is for the color screen radios.
<br />
- [x] It would be nice if the Outputs screen had something to indicate channel positions and/or movement. OpenTX has a little arrow that points towards the min or max depending on position, or a dash if at center. Makes it a bit easier than flipping back and forth from the mixes page to see what channel to go mess with. #1526

![Screenshot 2022-01-07 220541](https://user-images.githubusercontent.com/1323809/148633633-31113e63-8331-470c-9952-ef7e61faee05.png)

- [x] Having the current us value on each row would be nice too, or if that's too CPU intensive, do it like the B&W radios and show it in the bar that says "OUTPUTS" for whichever row is highlighted. #1664
<br />

- [x] Borrowing the top bar of the Mixes edit screen for the Outputs edit screen would be good too. Maybe also some kind of indicator next to Min and Max to indicate where it is when you want to change end points. Or perhaps simply label Min and Max within the little output graph? #1526 #1664

![screen-2022-01-07-222741](https://user-images.githubusercontent.com/1323809/148634324-6a4d5dc2-917f-46fd-83c9-f5d6c6ed9876.png)
<br />

- [ ] The B&W radios also have a feature where if you long press on an output, it offers an option for "copy the min/max/center to all." Would be nice to see this on the color radios too.

**Comment by micromega1966** [comment]
Era già stato chiesto qualche tempo fa con la versione 2.5 ma non è stato preso in considerazione. Peccato, sarebbe molto utile.

**Comment by natiho2** [comment]
I'm also surprised they do not address this,
it exists in every transmitter,
It feels like a body that is missing a very useful item..
In the meantime I went back to opentx until it fixed
If it will be fixed at all.

**Comment by raphaelcoeffic** [comment]
> I'm also surprised they do not address this, it exists in every transmitter, It feels like a body that is missing a very useful item.. 

We have all only 2 hands... But no worry, we know this is an issue.

> If it will be fixed at all.

Don't be rude 😅 You are very welcome to participate and help make things faster.

**Comment by MervDale** [comment]
> I'm also surprised they do not address this, it exists in every transmitter, It feels like a body that is missing a very useful item.. In the meantime I went back to opentx until it fixed If it will be fixed at all.

As in OpenTx you can name the Output channel(s) i.e. Channel 1 = Rudder,  if you are not sure which is which. 
 INV tells you if  you have reversed (Inverted) the channel so  OUTPUTS gives you pretty much everything OpenTx does except for two little arrows and a dash that tells you which way you are moving the stick,   I find it a bit odd if you're not sure of that !

**Comment by natiho2** [comment]
> > > I'm also surprised they do not address this, it exists in every transmitter, It feels like a body that is missing a very useful item.. In the meantime I went back to opentx until it fixed If it will be fixed at all.
> > 
> > 
> > As in OpenTx you can name the Output channel(s) i.e. Channel 1 = Rudder, if you are not sure which is which. INV tells you if you have reversed (Inverted) the channel so OUTPUTS gives you pretty much everything OpenTx does except for two little arrows and a dash that tells you which way you are moving the stick, I find it a bit odd if you're not sure of that !
> 
> and the value the output has at the moment. It´s actually really helpful when setting up big gliders for example.

You can also fly with a 4-channel remote control, you can also drive a car with mechanical window handles, etc.
I really do not understand the response you wrote
The two little arrows you mentioned are what make all the difference to an efficient setup

**Comment by natiho2** [comment]
> I'm also surprised they do not address this, it exists in every transmitter, It feels like a body that is missing a very useful item.. In the meantime I went back to opentx until it fixed If it will be fixed at all.
> 
> I really do not understand the response you wrote
> 
> Maybe you should stay with OpenTx then and can also look for the manners you seemed to have dropped on the way 😉

I'm sorry if you were hurt I did not mean that,
I mostly fly helicopters and there is no room for mistakes as you know
When you setup a helicopter the arrow on the output page is very helpful and true that it is possible even without it, but it mostly complicates things, after all we all switched to edgetx
Because it's a touch screen and program things faster and more efficiently.
