### ISSUE TITLE
main: widget interaction issues

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2182]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Regressions:
- [x] touch: Double tap on a widget no longer fullscreens widget - OK, intentional change... need to use menu to get fullscreen opt now (press and hold)
- [x] non-touch: If using rotary encoder to full-screen a built-in widget, there doesn't seem to be a way to make it exit fullscreen... except for the power button 🤪 . Lua widgets (i.e. Timer2, EventDemo) appear to be exit fullscreen properly on long RTN (fixed with c3660ab931a3cb5a2d0cc099366ced1a1444e51b). 
- [x] color picker: Widgets that have more than one color picker don't seem to work - i.e. outputs widget has three, and the first and second stay black, whilst the third works as expected.  Note, this is on simulator, and sometimes a widget that has a single color picker just comes up with a black colourwheel, or the knob is black and doesn't change color.  #2217 would resolve
- [x] top bar widgets - when you press and hold these, they now give widget settings menu (which is good) - but this also gives fullscreen option, which then breaks the top bar. 
- [x] some widgets - doesn't seem to be specific to cpp or Lua - don't seem to respond well to RTN to close the widget settings (when open from the main screen - not from the screen settings). Have to press RTN multiple times, long/short press... sometimes it works perfectly, often have to keep pressing multiple times - seems quite random when it will work. Touching outside the settings area always responds. The Gauge widget is a good offender, whereas the "Text" one is consistently responsive.  #2354
- [x] Need to close the widget options menu if anything else opened (i.e. main carousel to go to screen settings) - as otherwise the menu is still onscreen when you go into screen settings ;) #2354

### Expected Behavior

No comment

### Steps To Reproduce

1. Double tap on widget to your hearts content, with no fullscreen in sight...
---
1. Add a 'built-in' widget - i.e. Outputs or Models 
2. Long press ENT
3. Select said widget
4. Choose Fullscreen
5. Try to get out of fullscreen mode using long press of RTN (no cheating... no using the power button or unplugging the battery!!)

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

For refernece, using main as of a0770beb5f8616e2f14f2828de12b3ff8b1f3397

**Comment by richardclli** [comment]
I figured a problem in long scrolling list.  e.g. The protocol selection in MPM, everytime trying to scroll fast to reach the OMP protocol, nothing can be selected in the list and cannot exit the selection as well.  Will give more details when necessary.

**Comment by pfeerick** [comment]
I've actually seen that sort of behaviour now that you mention it, and not in the protocol selection list, but in the main sources lists... it seems to be if you have the list too long it stops responding - I've not thought to hunt it down further so can't be sure it's not a backlight timeout issue though.
