### ISSUE TITLE
2.8.0-RC1 Issue Tracker

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2363]
Known issues will be added to this issue as they arise, and are planned for fixing before the next RC or final release. 
- [x] Full screen LUA 1px offset - #2339
- [x] Potential Companion startup warning - #2365
- [x] Lua font alignment - #2370 
- [x] Default input names are one character shorter #2389
- [x] #2386
- [x] Labels import will resurrect deleted models still on radio #2373
- [x] X9D(+) & X9E volume (see 6fd69f8053e)
- [x] #2412
- [x] #2398
- [x] Companion: #2419
- [x] Channel Monitor -> Logical switches: Becomes unresponsive / not indicating LS state at all #2384 #2396

**RC2**
- [ ] font space sizes - #2372

**Comment by raphaelcoeffic** [comment]
Is that 1. April already? 🤓

**Comment by pfeerick** [comment]
Yup ;)

**Comment by Stinky80** [comment]
hmm... bugTracker???

**Comment by rlisch** [comment]
Downloaded latest Nightly to my touch screen upgraded Horus X12S. Now touch screen function is all over the place and not usable anymore. Returned to Saturday's release and all good.

**Comment by raphaelcoeffic** [comment]
@rlisch you need to reset the config of the touch controller, see here: https://github.com/EdgeTX/edgetx/pull/2351

**Comment by richardclli** [comment]
EL18 internal module settings missed the option to choose output type (PWM/PPM/SBUS/iBUS, etc.), this function is essential for EL18 to work properly with receivers.

**Comment by richardclli** [comment]
Channel selector in NV14/EL18 screen, the left tab bar is quite small and too close to the left.  Not sure if any tuning can be made to this popup,

**Comment by richardclli** [comment]
Should I please these findings in separate issue or attach to this one?

**Comment by Eldenroot** [comment]
One issue per bug/request would be better I think--- _¨¨)

**Comment by gagarinlg** [comment]
I agree, one issue per bug and just a reference here

**Comment by jfrickmann** [comment]
https://www.youtube.com/watch?v=tbKQN6bVlAQ

**Comment by pfeerick** [comment]
My X9D+ (*not* the 2019) is speaking with https://github.com/EdgeTX/edgetx/commit/6fd69f8053e807a1f70b7ede0d0c95c431e020a4, but it was with 2.8.0-rc1, so unless there is something else different with the X9E that may not be the cuplrit.

**Comment by TheIsotopes** [comment]
what about #2025. Nothing has changed yet.

**Comment by Gerold68** [comment]
> @Gerold68 this might be the cause of your issue: [6fd69f8](https://github.com/EdgeTX/edgetx/commit/6fd69f8053e807a1f70b7ede0d0c95c431e020a4). Since we don't use EEPROM anymore, the I2C bus is potentially not initialised, thus causing the volume setting to fail.

TNX

**Comment by richardclli** [comment]
@pfeerick  I have added 2 issues #2411 and #2412, these 2 will affect the mass production of EL18 planned in Nov, please add these in v2.8.0, thanks.

**Comment by pfeerick** [comment]
This is more an issue tracker for bugs reported for 2.8.0-RC1, so #2412 makes it onto this list. I would suggest it be targeted to be fixed for RC3, as think we have have enough things fixed to do RC2 shortly - particularly so we can get rid of the label EMs and Companion error. However, #2411 is on the 2.8.0 milestone.

**Comment by yds** [comment]
flashed 6fd69f8 https://github.com/EdgeTX/edgetx/actions/runs/3141800150
volume works fine.. I have the same GF setting pot1 as volume on my X9E -- all good now. 🤘

**Comment by TheIsotopes** [comment]
Ghost menu can no longer be operated via scroll key in latest RC, but it still worked with v2.7.1.

**Comment by Eldenroot** [comment]
Would be nice to have another issue for tracking progress for LVGL rewrite of screens :)

**Comment by raphaelcoeffic** [comment]
> Would be nice to have another issue for tracking progress for LVGL rewrite of screens :)

We have "Projects" for this, to which issues can be added. Not sure we have a (meta) issue that summarises which screen still need to converted.
