### ISSUE TITLE
2.8.0-RC2 Issue Tracker

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2447]
Known issues will be added to this issue as they arise, and are planned for fixing before the next RC or final release.
- wont fix - font space sizes - #2372 
- [x] color: https://github.com/EdgeTX/edgetx/issues/2452
- [x] #2478
- [x] #2460
- [x] source/switch list toolbar issues - lists appear blank when using filters, filters not mutually exclusive - #2445
- [x] missing characters in LUA scripts - #2446 
- [x] max length model names have weird characters in labels.yml - #2444
- [x] https://github.com/EdgeTX/edgetx/issues/2457
- [x] #2477
- [x] https://github.com/EdgeTX/edgetx/issues/2496
- [x] https://github.com/EdgeTX/edgetx/issues/2500
- [x] https://github.com/EdgeTX/edgetx/issues/2284 (hopefully fixed by https://github.com/EdgeTX/libopenui/pull/77)
