### ISSUE TITLE
LVGL Flex Layout: finish screen conversions

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/edgetx#2522]
### Description

Release `2.8` is still considered a "transition release", as it is already using LVGL, but some screens are still using the old layouts where every control is set at specific coordinates, and most of the screen is completely recreated on each and every change.

### TODOs

The following screens still need to be converted to flex layout:
- [x] Global functions (consider #2088)https://github.com/EdgeTX/edgetx/pull/2992
- [x] Curves (on-going work / #2090 / #2508, consider #2557,  #2556) https://github.com/EdgeTX/edgetx/pull/3041
- [x] Global variables #2945  (also consider #2498)
- [x] Logical Switches (consider #2808) https://github.com/EdgeTX/edgetx/pull/3019
- [x] Special Functions (consider #2088) https://github.com/EdgeTX/edgetx/pull/2992
- [x] Custom scripts - https://github.com/EdgeTX/edgetx/pull/3071
- [x] Telemetry https://github.com/EdgeTX/edgetx/pull/3070

Per https://github.com/EdgeTX/edgetx/issues/2522#issuecomment-1399203130
- [x] Statistics & Debug (PR #3072)
- [x] Logical Switches Monitor (added to PR #3019)
- [x] Theme Details (PR #3078)
- [x] Spectrum Analyser (footer) (PR #3077)
- [x] Select Template Folder (PR #3076)

**Comment by mha1** [comment]
Hi, can you please check https://github.com/EdgeTX/edgetx/issues/2818 and point me in the right direction how to fix this? See comments for what I tried and failed miserably.

**Comment by philmoz** [comment]
Global / Special functions - #2992 
Logical Switches - #3019 

I was going to look at telemetry next if no one else is doing it.

**Comment by pfeerick** [comment]
I'm planning to at looking those two PRs and also the Curves one early next week... have just been giving them time for the discussions to finish ;)

**Comment by philmoz** [comment]
Telemetry - #3070

**Comment by philmoz** [comment]
Custom mixer scripts - #3071

**Comment by Eldenroot** [comment]
Are these all non-converted screens? Any new finding?

**Comment by gagarinlg** [comment]
I think that's it

**Comment by philmoz** [comment]
There are still some pages using the FormGridLayout class and direct painting into the bitmap buffer:
- Statistics & Debug
- Logical Switches Monitor
- Theme Details
- Spectrum Analyser (footer)
- Select Template Folder

**Comment by Eldenroot** [comment]
Good job, only few issues left from the first post!!!

**Comment by pfeerick** [comment]
With the merge of the custom script page, this brings to an end the bulk of the LVGL conversion for colorlcd. There is still more work to be done, and improvements that can be made, but this will now mostly flow on from this conversion effort.
